3-a: 3-a.c
	gcc -Wall -pthread 3-a.c -o 3-a

3-a2: 3-a2.c
	gcc -Wall -pthread 3-a2.c -o 3-a2

3-b: 3-b.c
	gcc -Wall -pthread 3-b.c -o 3-b

3-c: 3-c.c
	gcc -Wall -pthread 3-c.c -o 3-c

clean:
	rm -f  3-a 3-a2 3-b 3-c
