mycp: mycp.c
	gcc -Wall mycp.c -o mycp
mycp2_1: mycp2_1.c
	gcc -Wall mycp2_1.c -o mycp2_1

mycp2_8192: mycp2_8192.c
	gcc -Wall mycp2_8192.c -o mycp2_8192

mycp_time_1: mycp_time_1.c
	gcc -Wall mycp_time_1.c -o mycp_time_1

mycp_time_8192: mycp_time_8192.c
	gcc -Wall mycp_time_8192.c -o mycp_time_8192

mywc: mywc.c
	gcc -Wall mywc.c -o mywc

2-a: 2-a.c
	gcc -Wall 2-a.c -o 2-a

clean:
	rm -f 2-a mycp mycp2_1 mycp2_8192 mycp_time_1 mycp_time_8192 mywc 2-a
